/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import projectcinema.Database;

/**
 *
 * @author User
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PhoneM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EmailM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DateM = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        AddrM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PassM = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Member");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRATION FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 11, -1, 25));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 50, -1, -1));

        NameM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameMActionPerformed(evt);
            }
        });
        getContentPane().add(NameM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 47, 186, -1));

        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 88, -1, -1));
        getContentPane().add(PhoneM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 85, 186, -1));

        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 147, -1, -1));

        EmailM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailMActionPerformed(evt);
            }
        });
        getContentPane().add(EmailM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 147, 186, -1));

        jLabel5.setText("Date of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 116, -1, -1));

        DateM.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(DateM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 116, 142, -1));

        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 207, -1, -1));

        AddrM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddrMActionPerformed(evt);
            }
        });
        getContentPane().add(AddrM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 204, 186, -1));

        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 176, -1, -1));
        getContentPane().add(PassM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 173, 134, -1));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 251, -1, -1));

        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 251, -1, -1));

        setBounds(0, 0, 353, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void NameMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameMActionPerformed

    private void EmailMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailMActionPerformed

    private void AddrMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddrMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddrMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (NameM.getText().equals("") || PhoneM.getText().equals("") || DateM.getDate().equals("") || EmailM.getText().equals("") || PassM.getText().equals("") || AddrM.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "You have to fill all");
        }else{
            try {
              String sql = "INSERT INTO member VALUES(NULL,'"+NameM.getText() + "','" + PhoneM.getText() + "','" + DateM.getDate()+ "','" +EmailM.getText() + "','" + PassM.getText() + "','" + AddrM.getText() +"','Active')";
              java.sql.Connection conn = (Connection) Database.configDB();
              java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
              pstm.execute();
              JOptionPane.showMessageDialog(null, "Registered Successfully");
              dispose();
              new LoginForm().setVisible(true);
            }catch (HeadlessException | SQLException e) {
              JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddrM;
    private com.toedter.calendar.JDateChooser DateM;
    private javax.swing.JTextField EmailM;
    private javax.swing.JTextField NameM;
    private javax.swing.JTextField PassM;
    private javax.swing.JTextField PhoneM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

}
